osqa/forum_modules/exporter/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.utils.translation import ugettext as _

from views import state, running, download

urlpatterns = patterns('',
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('state/')),  state, name='exporter_state'),
    url(r'^%s(?P<mode>\w+)/%s$' % (_('admin/'), _('running/')),  running, name='exporter_running'),
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('download/')),  download, name='exporter_download'),
)

osqa/forum_modules/facebookauth/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from views import user_is_registered

urlpatterns = patterns('',
    url(r'^xd_receiver.htm$',  direct_to_template,  {'template': 'modules/facebookauth/xd_receiver.html'}, name='xd_receiver'),
    url(r'^facebook/user_is_registered/', user_is_registered, name="facebook_user_is_registered"),
)

osqa/forum_modules/robotstxt/urls.py
from django.conf.urls.defaults import *
from django.http import  HttpResponse
import settings

urlpatterns = patterns('',
    (r'^robots.txt$',  lambda r: HttpResponse(settings.ROBOTS_FILE.value)),
)

osqa/urls.py
from django.conf.urls.defaults import *
from django.utils.translation import ugettext as _
from django.conf import settings

urlpatterns = patterns('',
    (r'', include('forum.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

handler404 = 'forum.views.meta.page'
handler500 = 'forum.views.meta.error_handler'

osqa/forum/models/base.py
import datetime
import re
from urllib import quote_plus, urlencode
from django.db import models, IntegrityError, connection, transaction
from django.utils.http import urlquote  as django_urlquote
from django.utils.html import strip_tags
from django.core.urlresolvers import reverse
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache
from django.template.defaultfilters import slugify
from django.db.models.signals import post_delete, post_save, pre_save, pre_delete
from django.utils.translation import ugettext as _
from django.utils.safestring import mark_safe
from django.contrib.sitemaps import ping_google
import django.dispatch
from forum import settings
import logging


class LazyQueryList(object):
    def __init__(self, model, items):
        self.items = items
        self.model = model

    def __getitem__(self, k):
        return self.model.objects.get(id=self.items[k][0])

    def __iter__(self):
        for id in self.items:
            yield self.model.objects.get(id=id[0])

    def __len__(self):
        return len(self.items)

class CachedQuerySet(models.query.QuerySet):

    def lazy(self):
        if not len(self.query.aggregates):
            values_list = ['id']

            if len(self.query.extra):
                extra_keys = self.query.extra.keys()
                values_list += extra_keys

            return LazyQueryList(self.model, list(self.values_list(*values_list)))
        else:
            if len(self.query.extra):
                print self.query.extra
            return self

    def obj_from_datadict(self, datadict):
        obj = self.model()
        obj.__dict__.update(datadict)
        return obj

    def get(self, *args, **kwargs):
        key = self.model.infer_cache_key(kwargs)

        if key is not None:
            obj = cache.get(key)

            if obj is None:
                obj = super(CachedQuerySet, self).get(*args, **kwargs)
                obj.cache()
            else:
                obj = self.obj_from_datadict(obj)
                obj.reset_original_state()

            return obj

        return super(CachedQuerySet, self).get(*args, **kwargs)

class CachedManager(models.Manager):
    use_for_related_fields = True

    def get_query_set(self):
        return CachedQuerySet(self.model)

    def get_or_create(self, *args, **kwargs):
        try:
            return self.get(*args, **kwargs)
        except:
            return super(CachedManager, self).get_or_create(*args, **kwargs)


class DenormalizedField(object):
    def __init__(self, manager, *args, **kwargs):
        self.manager = manager
        self.filter = (args, kwargs)

    def setup_class(self, cls, name):
        dict_name = '_%s_dencache_' % name

        def getter(inst):
            val = inst.__dict__.get(dict_name, None)

            if val is None:
                val = getattr(inst, self.manager).filter(*self.filter[0], **self.filter[1]).count()
                inst.__dict__[dict_name] = val
                inst.cache()

            return val

        def reset_cache(inst):
            inst.__dict__.pop(dict_name, None)
            inst.uncache()

        cls.add_to_class(name, property(getter))
        cls.add_to_class("reset_%s_cache" % name, reset_cache)


class BaseMetaClass(models.Model.__metaclass__):
    to_denormalize = []

    def __new__(cls, *args, **kwargs):
        new_cls = super(BaseMetaClass, cls).__new__(cls, *args, **kwargs)

        BaseMetaClass.to_denormalize.extend(
            [(new_cls, name, field) for name, field in new_cls.__dict__.items() if isinstance(field, DenormalizedField)]
        )

        return new_cls

    @classmethod
    def setup_denormalizes(cls):
        for new_cls, name, field in BaseMetaClass.to_denormalize:
            field.setup_class(new_cls, name)


class BaseModel(models.Model):
    __metaclass__ = BaseMetaClass

    objects = CachedManager()

    class Meta:
        abstract = True
        app_label = 'forum'

    def __init__(self, *args, **kwargs):
        super(BaseModel, self).__init__(*args, **kwargs)
        self.reset_original_state(kwargs.keys())

    def reset_original_state(self, reset_fields=None):
        self._original_state = self._as_dict()
        
        if reset_fields:
            self._original_state.update(dict([(f, None) for f in reset_fields]))

    def get_dirty_fields(self):
        return [f.name for f in self._meta.fields if self._original_state[f.attname] != self.__dict__[f.attname]]

    def _as_dict(self):
        return dict([(name, getattr(self, name)) for name in
                     ([f.attname for f in self._meta.fields] + [k for k in self.__dict__.keys() if k.endswith('_dencache_')])
        ])

    def _get_update_kwargs(self):
        return dict([
            (f.name, getattr(self, f.name)) for f in self._meta.fields if self._original_state[f.attname] != self.__dict__[f.attname]
        ])

    def save(self, full_save=False, *args, **kwargs):
        put_back = [k for k, v in self.__dict__.items() if isinstance(v, models.expressions.ExpressionNode)]

        if self.id and not full_save:
            self.__class__.objects.filter(id=self.id).update(**self._get_update_kwargs())
        else:
            super(BaseModel, self).save()

        if put_back:
            try:
                self.__dict__.update(
                    self.__class__.objects.filter(id=self.id).values(*put_back)[0]
                )
            except:
                logging.error("Unable to read %s from %s" % (", ".join(put_back), self.__class__.__name__))
                self.uncache()

        self.reset_original_state()
        self.cache()

    @classmethod
    def _generate_cache_key(cls, key, group=None):
        if group is None:
            group = cls.__name__

        return '%s:%s:%s' % (settings.APP_URL, group, key)

    def cache_key(self):
        return self._generate_cache_key(self.id)

    @classmethod
    def infer_cache_key(cls, querydict):
        try:
            pk = [v for (k,v) in querydict.items() if k in ('pk', 'pk__exact', 'id', 'id__exact'
                            ) or k.endswith('_ptr__pk') or k.endswith('_ptr__id')][0]

            return cls._generate_cache_key(pk)
        except:
            return None

    def cache(self):
        cache.set(self.cache_key(), self._as_dict(), 60 * 60)

    def uncache(self):
        cache.delete(self.cache_key())

    def delete(self):
        self.uncache()
        super(BaseModel, self).delete()


from user import User
from node import Node, NodeRevision, NodeManager
from action import Action

osqa/forum/models/meta.py
from django.utils.translation import ugettext as _
from base import *

class Vote(models.Model):
    user = models.ForeignKey(User, related_name="votes")
    node = models.ForeignKey(Node, related_name="votes")
    value = models.SmallIntegerField()
    action = models.OneToOneField(Action, related_name="vote")
    voted_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        app_label = 'forum'
        unique_together = ('user', 'node')


class Flag(models.Model):
    user = models.ForeignKey(User, related_name="flags")
    node = models.ForeignKey(Node, related_name="flags")
    reason = models.CharField(max_length=300)
    action = models.OneToOneField(Action, related_name="flag")
    flagged_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        app_label = 'forum'
        unique_together = ('user', 'node')

class BadgesQuerySet(models.query.QuerySet):
    def get(self, *args, **kwargs):
        try:
            pk = [v for (k,v) in kwargs.items() if k in ('pk', 'pk__exact', 'id', 'id__exact')][0]
        except:
            return super(BadgesQuerySet, self).get(*args, **kwargs)

        from forum.badges.base import BadgesMeta
        badge = BadgesMeta.by_id.get(int(pk), None)
        if not badge:
            return super(BadgesQuerySet, self).get(*args, **kwargs)
        return badge.ondb


class BadgeManager(models.Manager):
    use_for_related_fields = True

    def get_query_set(self):
        return BadgesQuerySet(self.model)

class Badge(models.Model):
    GOLD = 1
    SILVER = 2
    BRONZE = 3

    type        = models.SmallIntegerField()
    cls         = models.CharField(max_length=50, null=True)
    awarded_count = models.PositiveIntegerField(default=0)
    
    awarded_to    = models.ManyToManyField(User, through='Award', related_name='badges')

    objects = BadgeManager()

    @property
    def name(self):
        cls = self.__dict__.get('_class', None)
        return cls and cls.name or _("Unknown")

    @property
    def description(self):
        cls = self.__dict__.get('_class', None)
        return cls and cls.description or _("No description available")

    @models.permalink
    def get_absolute_url(self):
        return ('badge', [], {'id': self.id, 'slug': slugify(self.name)})

    def save(self, *args, **kwargs):
        if isinstance(self.awarded_count, models.expressions.ExpressionNode):
            super(Badge, self).save(*args, **kwargs)
            self.awarded_count = self.__class__.objects.filter(id=self.id).values_list('awarded_count', flat=True)[0]
        else:
            super(Badge, self).save(*args, **kwargs)


    class Meta:
        app_label = 'forum'


class Award(models.Model):
    user = models.ForeignKey(User)
    badge = models.ForeignKey('Badge', related_name="awards")
    node = models.ForeignKey(Node, null=True)

    awarded_at = models.DateTimeField(default=datetime.datetime.now)

    trigger = models.ForeignKey(Action, related_name="awards", null=True)
    action = models.OneToOneField(Action, related_name="award")


    class Meta:
        unique_together = ('user', 'badge', 'node')
        app_label = 'forum'

osqa/forum/models/tag.py
import datetime
from base import *

from django.utils.translation import ugettext as _

from forum import modules

class ActiveTagManager(models.Manager):
    def get_query_set(self):
        return super(ActiveTagManager, self).get_query_set().exclude(used_count__lt=1)

class Tag(BaseModel):
    name            = models.CharField(max_length=255, unique=True)
    created_by      = models.ForeignKey(User, related_name='created_tags')
    created_at      = models.DateTimeField(default=datetime.datetime.now, blank=True, null=True)
    marked_by       = models.ManyToManyField(User, related_name="marked_tags", through="MarkedTag")
    # Denormalised data
    used_count = models.PositiveIntegerField(default=0)

    active = ActiveTagManager()

    class Meta:
        ordering = ('-used_count', 'name')
        app_label = 'forum'

    def __unicode__(self):
        return u'%s' % self.name

    def add_to_usage_count(self, value):
        if self.used_count + value < 0:
            self.used_count = 0
        else:
            self.used_count = models.F('used_count') + value

    @models.permalink
    def get_absolute_url(self):
        return ('tag_questions', (), {'tag': self.name})

class MarkedTag(models.Model):
    TAG_MARK_REASONS = (('good', _('interesting')), ('bad', _('ignored')))
    tag = models.ForeignKey(Tag, related_name='user_selections')
    user = models.ForeignKey(User, related_name='tag_selections')
    reason = models.CharField(max_length=16, choices=TAG_MARK_REASONS)

    class Meta:
        app_label = 'forum'

osqa/forum/forms/admin.py
import socket
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.admin.widgets import FilteredSelectMultiple, AdminDateWidget
from qanda import TitleField, EditorField
from forum import settings
from forum.models.node import NodeMetaClass
from forum.models import User

class IPListField(forms.CharField):
    def clean(self, value):
        ips = [ip.strip() for ip in value.strip().strip(',').split(',')]
        iplist = []

        if len(ips) < 1:
            raise forms.ValidationError(_('Please input at least one ip address'))

        for ip in ips:
            try:
                socket.inet_aton(ip)
            except socket.error:
                raise forms.ValidationError(_('Invalid ip address: %s' % ip))

            if not len(ip.split('.')) == 4:
                raise forms.ValidationError(_('Please use the dotted quad notation for the ip addresses'))

            iplist.append(ip)

        return iplist

class MaintenanceModeForm(forms.Form):
    ips = IPListField(label=_('Allow ips'),
                      help_text=_('Comma separated list of ips allowed to access the site while in maintenance'),
                      required=True,
                      widget=forms.TextInput(attrs={'class': 'longstring'}))

    message = forms.CharField(label=_('Message'),
                              help_text=_('A message to display to your site visitors while in maintainance mode'),
                              widget=forms.Textarea)


TEMPLATE_CHOICES = (
('default', _('Default')),
('sidebar', _('Default with sidebar')),
('none', _('None')),
)

RENDER_CHOICES = (
('markdown', _('Markdown')),
('html', _('HTML')),
('escape', _('Escaped'))
)

class UrlFieldWidget(forms.TextInput):
    def render(self, name, value, attrs=None):
        if not value:
            value = ''

        return """
                <input class="url_field" type="text" name="%(name)s" value="%(value)s" />
                <a class="url_field_anchor" target="_blank" href="%(app_url)s"></a>
            """  % {'name': name, 'value': value, 'app_url': settings.APP_URL}


class PageForm(forms.Form):
    def __init__(self, page, *args, **kwargs):
        if page:
            initial = page.extra
            initial.update(dict(title=page.title, content=page.body))
            super(PageForm, self).__init__(initial=initial, *args, **kwargs)
        else:
            super(PageForm, self).__init__(*args, **kwargs)


    title  = forms.CharField(label=_('Title'), max_length=255, widget=forms.TextInput(attrs={'class': 'longstring'}),
                             initial='New page')
    path  = forms.CharField(label=_('Page URL'), widget=UrlFieldWidget, initial='pages/new/')

    content = forms.CharField(label=_('Page Content'), widget=forms.Textarea(attrs={'rows': 30}))
    mimetype = forms.CharField(label=_('Mime Type'), initial='text/html')

    render = forms.ChoiceField(widget=forms.RadioSelect, choices=RENDER_CHOICES, initial='markdown',
                               label=_('Render Mode'))

    template = forms.ChoiceField(widget=forms.RadioSelect, choices=TEMPLATE_CHOICES, initial='default',
                                 label=_('Template'))
    sidebar = forms.CharField(label=_('Sidebar Content'), widget=forms.Textarea(attrs={'rows': 20}), required=False)
    sidebar_wrap = forms.BooleanField(label=_("Wrap sidebar block"), initial=True, required=False)
    sidebar_render = forms.ChoiceField(widget=forms.RadioSelect, choices=RENDER_CHOICES, initial='markdown',
                                       label=_('Sidebar Render Mode'))

    comments = forms.BooleanField(label=_("Allow comments"), initial=False, required=False)

from forum.forms.auth import SimpleRegistrationForm
from forum.forms.general import SetPasswordForm


class CreateUserForm(SimpleRegistrationForm, SetPasswordForm):
    validate_email = forms.BooleanField(required=False, label=_('send validation email'))

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['username', 'email', 'validate_email', 'password1', 'password2']
        self.fields['email'].label = _('email address')


    

osqa/forum/skins/fresh/templates/401.html
{% extends "base_content.html" %}
{% load i18n %}
{% block title %}{% trans "Not logged in" %}{% endblock %}
{% block meta %}
    <!-- <meta http-equiv="refresh" content="5;url={% url auth_signin %}"> -->
{% endblock %}
{% block forestyle%}
    <style type="text/css">
 		form input { margin-right: 5px; }
	</style>
{% endblock %}
{% block forejs %}
       <script type="text/javascript">
        $().ready(function(){
            window.setInterval(function() {
                $('#redirect_loader').html($('#redirect_loader').html() + '.')
            }, 800);

            window.setTimeout(function() {
                window.location = "{% url auth_signin %}";
            }, 5000);
        });

        </script>
{% endblock %}
{% block content %}
<div id="main-bar" class="headNormal">
    {% trans "Not logged in" %}
</div>
<div id="main-body" class="">
    <div style="padding:5px 0px 10px 0;line-height:25px;">
        <h3>{% trans "You are not logged in..." %}</h3>
        <div style="margin-top:5px">
            {% trans "...and the resource you're trying to access is protected." %}
            <p>
                {% trans "Redirecting to the login page." %}<span id="redirect_loader"></span>
            </p>
            <p>
                {% trans "If you're not automatically redirected in 5 seconds, please click" %}
                <a href="{% url auth_signin %}">{% trans "here" %}</a>.
            </p>
        </div>
    </div>

</div>
{% endblock %}

osqa/forum/skins/fresh/templates/account_settings.html
{% extends "base_content.html" %}
<!-- settings.html -->
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Account functions" %}{% endspaceless %}{% endblock %}
{% block head %}
<style type="text/css" media="screen">
    h4 {font-size:12pt;}
	dt, dd { padding:0 0 0.35em 0; }
	dt { float: left; width: 21ex;  }
	dd { margin-left: 23ex;  }
	
	#settings-options, #settings-intro { padding: 4em 1.5em;}
	#settings-options { min-height: 300px; border-left: 1px solid #333;}
	
	#settings-options h5 { font-weight: bold;}
</style>
{% endblock %}

{% block content %}
<div id="main-bar">
    <h3><strong>{{ request.user.username }} {% trans "Profile" %}</strong></h3>
</div>
<div id="settings-options">
	{% if msg %}
		<p class="error">{{ msg }}</p>
	{% endif %}

	<dl class="list-item">
        <dt>&raquo; <a href="{% url user_changepw %}">{% trans "Change password" %}</a></dt>
        <dd>{% trans "Give your  account a new password." %}</dd>
        {% comment %}
        <dt>&raquo; <a href="{% url user_changeemail %}">{% trans "Change email " %}</a></dt>
        <dd>{% trans "Add or update the email address associated with your account." %}</dd>

        <dt>&raquo; <a href="{% url user_changeopenid %}">{% trans "Change OpenID" %}</a></dt>
        <dd>{% trans "Change openid associated to your account" %}</dd>

        
        <dt>&raquo; <a href="{% url user_delete %}">{% trans "Delete account" %}</a></dt>
        <dd>{% trans "Erase your username and all your data from website" %}</dd>
        {% endcomment %}
	</dl>
</div>
{% endblock %}
<!-- end settings.html -->

osqa/forum/skins/fresh/templates/answer_edit_tips.html
<!-- template answer_edit_tips.html -->
{% load i18n general_sidebar_tags %}
<div class="boxC">
    <p class="subtitle darkred">{% trans "answer tips" %}</p>
    <div>
        <ul class="list-item">
            <li> <b>{% trans "please make your answer relevant to this community" %}</b>
            </li>
            <li>
                {% trans  "try to give an answer, rather than engage into a discussion" %}
            </li>
            <li>
                {% trans "please try to provide details" %}
            </li>
            <li>
				{% trans "be clear and concise" %}
            </li>
        </ul>
        <p class='info-box-follow-up-links'>
            <a href="{% url faq %}" target="_blank" title="{% trans "see frequently asked questions" %}">faq &raquo;</a>
        </p>
    </div>
</div>

{% markdown_help %}
<!-- end template answer_edit_tips.html -->

osqa/forum/skins/fresh/templates/ask.html
{% extends "base.html" %}
<!-- template ask.html -->
{% load i18n extra_tags extra_filters %}
{% block title %}{% spaceless %}{% trans "Ask a question" %}{% endspaceless %}{% endblock %}
{% block forejs %}
        <script type='text/javascript' src='{% media  "/media/js/wmd/showdown.js" %}'></script>
        <script type='text/javascript' src='{% media  "/media/js/wmd/wmd.js" %}'></script>
        <link rel="stylesheet" type="text/css" href="{% media  "/media/js/wmd/wmd.css" %}" />
        <script type="text/html" id="question-summary-template">
            <div class="answer-summary">
                <a href="%URL%"><div class="answer-votes">%SCORE%</div></a>
                <div class="answer-link">
                    <a class="question-hyperlink" href="%URL%" title="%SUMMARY%">%TITLE%</a>
                </div>
            </div>
        </script>
        <script type="text/javascript">
        $(function(){
            //set current module button style
            $("#nav_ask").attr('className',"on");
            $('#editor').TextAreaResizer();

            //toggle preview of editor
			//todo remove copy-paste
            var display = true;
            var txt = "[{% trans "hide preview" %}]";
            $('#pre-collapse').text(txt);
            $('#pre-collapse').bind('click', function(){
                txt = display ? "[{% trans "show preview" %}]" : "[{% trans "hide preview" %}]";
                display = !display;
                $('#previewer').toggle();
                $('#pre-collapse').text(txt);
            });

            //Tags autocomplete action
        	$("#id_tags").autocomplete("{% url matching_tags %}", {
                minChars: 1,
        		matchContains: true,
                max: 10,
                multiple: true,
                multipleSeparator: " ",
                highlightItem: true,
                scroll: true,
                scrollHeight: 300,


        		/*
        		formatItem: function(row, i, max) {
        			return row.n + " ("+ row.c +")";
        		},
                formatResult: function(row, i, max){
                    return row.n;
                }
                */

                formatItem: function(row, i, max, value) {
                    return row[1] + " (" + row[2] + ")";
                },

                formatResult: function(row, i, max, value){
                    return row[1];
                }

            });

        });

        function submitClicked(e, f) {
            if(!(browserTester('chrome') || browserTester('safari'))) {
                $("input.submit")[0].disabled=true;
            }
            window.removeEventListener('beforeunload', beforeUnload, true);
            if (f) {
                f.submit();
            }
        }

        function beforeUnload(e) {
            if($("input#id_title")[0].value != "" || $("textarea#editor")[0].value != "" || $("input#id_tags")[0].value != "") {
                return yourWorkWillBeLost(e);
            }
        }
        window.addEventListener('beforeunload', beforeUnload, true);

        var related_questions_url = "{% url related_questions %}";
        </script>
        <script src="{% media "/media/js/osqa.ask.js" %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
<div id="main-bar" class="headNormal">
	{% trans "Ask a question" %}
</div>
<div id="main-body" class="ask-body">
    <div id="askform">
        <form id="fmask" action="" method="post" accept-charset="utf-8">
            {% csrf_token %}
			{% if not request.user.is_authenticated %}
            <div class="message">
                <span class="strong big">{% trans "You are welcome to start submitting your question anonymously." %}</span>
                <p>{% blocktrans %}
                    After submiting your question, you will be redirected to the login/signup page.
                    Your question will be saved in the current session and will be published after you login with your existing account,
                    or signup for a new account{% endblocktrans %}{% if "ask"|contained_in:settings.REQUIRE_EMAIL_VALIDATION_TO %}
                    {% trans "and validate your email." %}{% else %}.{% endif %}</p>
            </div>
            {% else %}
                {% if not request.user.email_valid_and_can_ask %}
                    <div class="message">
                        {% blocktrans %}Remember, your question will not be published until you validate your email.{% endblocktrans %}
                        <a href="{% url send_validation_email %}">{% trans "Send me a validation link." %}</a>
                    </div>
                {% endif %}
			{% endif %}
            <div class="form-item">
                <label for="id_title" ><strong>{{ form.title.label_tag }}:</strong></label> <span class="form-error"></span><br/>
                {{ form.title }} {{ form.title.errors }}
                <div class="title-desc">
                    {{ form.title.help_text }}
                </div>
            </div>
            <div id="ask-related-questions"></div>
            <div class="form-item">
                <div id="wmd-button-bar" class="wmd-panel"></div>
                {{ form.text }} {{ form.text.errors }}
                <div class="preview-toggle">
                    <table width="100%">
                        <tr>
                            <td>
                                <span id="pre-collapse" title="{% trans "Toggle the real time Markdown editor preview" %}">{% trans "toggle preview" %}</span>
                            </td>
                            <td style="text-align: right;" id="editor-metrics"></td>
                            {% if settings.WIKI_ON %}
                            <td class="tright">
                                {{ form.wiki }} <span class="help_text" title="{{form.wiki.help_text}}">{{ form.wiki.label_tag }} </span>
                            </td>
                            {% endif %}
                        </tr>

                    </table>
                </div>
                <div id="previewer" class="wmd-preview"></div>
                <span class="form-error"></span>
            </div>
            <div class="form-item">
                <strong>{{ form.tags.label_tag }}:</strong> {% trans "(required)" %} <span class="form-error"></span><br/>
                {{ form.tags }}  {{ form.tags.errors }}
            </div>
			<p class="title-desc">
				{{ form.tags.help_text }}
			</p>
			
            {% if form.recaptcha %}
            <div class="question-captcha" style="float: left">
            	{{ form.recaptcha.errors }}
            	{{ form.recaptcha }}
            </div>
            <div class="clear"></div>
            {% endif %}
			
            {% if not request.user.is_authenticated %}                                                                        
            <input name="ask" type="button" value="{% trans "Login/signup to post your question" %}" class="submit" onclick="submitClicked(event, this.form)"/>
			{% else %}
            <input name="ask" type="button" value="{% trans "Ask your question" %}" class="submit" onclick="submitClicked(event, this.form)"/>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

{% block sidebar %}
{% include "question_edit_tips.html" %}
{% endblock %}

{% block endjs %}
{% endblock %}
<!-- end template ask.html -->

osqa/forum/skins/fresh/templates/badge.html
{% extends "base_content.html" %}
<!-- template badge.html -->
{% load i18n %}
{% load extra_tags %}
{% load user_tags %}
{% load humanize %}
{% block title %}{% spaceless %}{{ badge.name }} - {% trans "Badge" %}{% endspaceless %}{% endblock %}
{% block forejs %}
       <script type="text/javascript">
        $().ready(function(){
            $("#nav_badges").attr('className',"on");
        });
         
        </script>
{% endblock %}
{% block content %}
<div id="main-bar" class="headNormal">
	{% trans "Badge" %}
</div>
<div id="main-body" style="width:100%;margin-bottom:20px">
    <p>
        <a href="{{badge.get_absolute_url}}" title="{{ badge.get_type_display }} : {{ badge.description }}" class="medal"><span class="badge{{ badge.type }}">&#9679;</span>&nbsp;{{ badge.name }}</a> {{ badge.description }}
    </p>
    <div>
        {% if badge.awarded_count %}
        <p style="float:left"><span class="count">{{ award_count|intcomma }}</span>
        <strong>{% trans "The users have been awarded with badges:" %}</strong></p>
        {% endif %}
    </div>
    <div id="award-list" style="clear:both;margin-left:20px;line-height:25px;">
        {% for award in awards %}
        <p style="width:220px;float:left">{% user_signature award.user "badges" %}<span class="tag-number"> &#215; {{ award.count|intcomma }}</span></p>
        {% endfor %}
    </div>

</div>
{% endblock %}
<!-- end template badge.html -->

osqa/forum/skins/fresh/templates/email_base.html
{% load extra_filters %}
{% load extra_tags %}
{% load email_tags %}
{% load i18n %}

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <style type="text/css">
            body {
                background: #FFF;
                font-size: 12px;
                line-height: 150%;
                margin: 0;
                padding: 0;
                color: #000;
                font-family: sans-serif;
            }

            #wrapper {
                width: 600px;
                margin: auto;
                padding: 0;
            }

            a img {
                border: none;
            }
        </style>
    </head>
    <body>
        <a href="{% fullurl index %}">
            <img src="cid:logo" title="{% trans "home" %}" alt="{{settings.APP_TITLE}} logo"/>
        </a>
        <br />
        <p>{{ settings.APP_TITLE }}</p>
    <br /><br />
    <div id="wrapper">
            <div id="room">
                <div id="CALeft">
                    {% block content%}
                    {% endblock%}
                </div>
            </div>
            <div class="spacer3"></div>
        </div>
    </body>
</html>